[colors.primary]
background = '#1a110f'
foreground = '#f1dfda'
 
[colors.cursor]
text = '#f1dfda'
cursor = '#d8c2bc' 
 
[colors.vi_mode_cursor]
text = '#1a110f'
cursor = '#ffb59f' 
 
[colors.search.matches]
foreground = '#53433f' 
background = '#d8c58d' 
 
[colors.search.focused_match]
foreground = '#53433f' 
background = '#ffb59f' 
 
[colors.footer_bar]
foreground = '#53433f' 
background = '#f1dfda' 
 
[colors.hints.start]
foreground = '#53433f' 
background = '#e7bdb2' 
 
[colors.hints.end]
foreground = '#53433f' 
background = '#e7bdb2' 
 
[colors.selection]
text = '#1a110f'
background = '#ffb59f'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb59f' 
yellow = '#8f4c38' 
blue = '#ffb59f' 
magenta = '#d8c58d' 
cyan = '#e7bdb2' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
